# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostconductor" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "cb99d0c78666cd56fbb829711d9dcf623f7acb05c5785d5d12e3f7b46dc95ba1"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "738fc5b05b16c753155189b906d925a5a4638d3543df86b25ac56a33dc8cbead"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "81a0d661877480941e6267511fd00cedc2229a03f21e11d13d987c33e1cfe56d"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-linux-amd64.tar.gz"
    end
  end

  name "ghostconductor"
  desc "AI agent orchestration platform"
  homepage "https://ghostconductor.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostconductor"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghostconductor"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/etc/prompts/intent"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/etc/context"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/jobs"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/repos"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/shared"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "/tmp/prompts.tar.gz", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/prompts.tar.gz"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "/tmp/context.tar.gz", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/context.tar.gz"]
    system_command "/usr/bin/tar", args: ["-xzf", "/tmp/prompts.tar.gz", "-C", "#{Dir.home}/ghostconductor/etc"]
    system_command "/usr/bin/tar", args: ["-xzf", "/tmp/context.tar.gz", "-C", "#{Dir.home}/ghostconductor/etc"]
    system_command "/usr/bin/touch", args: ["#{Dir.home}/ghostconductor/etc/CONTEXT.md"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "#{Dir.home}/ghostconductor/etc/network-policy.json", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/network-policy.json"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "#{Dir.home}/ghostconductor/etc/container-policy.json", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/container-policy.json"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/etc/matrix/maps"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "/tmp/matrix.tar.gz", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/matrix.tar.gz"]
    system_command "/usr/bin/tar", args: ["-xzf", "/tmp/matrix.tar.gz", "-C", "#{Dir.home}/ghostconductor/etc"]
    system_command "/bin/rm", args: ["-f", "/tmp/prompts.tar.gz", "/tmp/context.tar.gz", "/tmp/matrix.tar.gz"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-rf", "#{Dir.home}/ghostconductor"]
    system_command "/bin/rm", args: ["-rf", "#{Dir.home}/.ghostconductor"]
    system_command "/usr/bin/env", args: ["docker", "rmi", "--force", "ghcr.io/ghostconductor/ghost:latest"], must_succeed: false
    system_command "/usr/bin/env", args: ["docker", "rmi", "--force", "ghcr.io/ghostconductor/ghost:dev"], must_succeed: false
  end

  # No zap stanza required

end
