# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostconductor" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "1a201ab6f6f7deb53df79106fd9a6412fb162e55c1fcb07fa7646f57a8c26f09"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "36fb9f2430ea4eedf069185c8dc2ff30dbe5a4c893edbc6ca2e8d06919743a3b"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "110308fd52db3155a23d8c0c197bb26cea6784a5fde53466b606149b073c677c"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-linux-amd64.tar.gz"
    end
  end

  name "ghostconductor"
  desc "AI agent orchestration platform"
  homepage "https://ghostconductor.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostconductor"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghostconductor"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/etc/prompts/intent"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/etc/context"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/jobs"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/repos"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/shared"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "/tmp/prompts.tar.gz", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/prompts.tar.gz"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "/tmp/context.tar.gz", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/context.tar.gz"]
    system_command "/usr/bin/tar", args: ["-xzf", "/tmp/prompts.tar.gz", "-C", "#{Dir.home}/ghostconductor/etc"]
    system_command "/usr/bin/tar", args: ["-xzf", "/tmp/context.tar.gz", "-C", "#{Dir.home}/ghostconductor/etc"]
    system_command "/usr/bin/touch", args: ["#{Dir.home}/ghostconductor/etc/CONTEXT.md"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "#{Dir.home}/ghostconductor/etc/network-policy.json", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/network-policy.json"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "#{Dir.home}/ghostconductor/etc/container-policy.json", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/container-policy.json"]
    system_command "/bin/rm", args: ["-f", "/tmp/prompts.tar.gz", "/tmp/context.tar.gz"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-rf", "#{Dir.home}/ghostconductor"]
    system_command "/bin/rm", args: ["-rf", "#{Dir.home}/.ghostconductor"]
    system_command "/usr/bin/env", args: ["docker", "rmi", "--force", "ghcr.io/ghostconductor/ghost:latest"]
    system_command "/usr/bin/env", args: ["docker", "rmi", "--force", "ghcr.io/ghostconductor/ghost:dev"]
  end

  # No zap stanza required

end
