# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostconductor" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "7f01a932b45d1359c58dd54debf9be75fd19adc712c262d1dc5eff23d398b343"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "7c0f72cdf628db00fab2293d12214fbfec3613c3a59e790a50edd25443a5a599"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bcd32e6d8d8996b2dce25643824f9b0f61879e3b340eb60431df0c3848a75f7f"
      url "https://github.com/GhostConductor/ghostconductor/releases/download/v#{version}/ghostconductor-linux-amd64.tar.gz"
    end
  end

  name "ghostconductor"
  desc "AI agent orchestration platform"
  homepage "https://ghostconductor.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostconductor"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghostconductor"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/etc/prompts/intent"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/etc/context"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/jobs"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/repos"]
    system_command "/bin/mkdir", args: ["-p", "#{Dir.home}/ghostconductor/shared"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "/tmp/prompts.tar.gz", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/prompts.tar.gz"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "/tmp/context.tar.gz", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/context.tar.gz"]
    system_command "/usr/bin/tar", args: ["-xzf", "/tmp/prompts.tar.gz", "-C", "#{Dir.home}/ghostconductor/etc"]
    system_command "/usr/bin/tar", args: ["-xzf", "/tmp/context.tar.gz", "-C", "#{Dir.home}/ghostconductor/etc"]
    system_command "/usr/bin/touch", args: ["#{Dir.home}/ghostconductor/etc/CONTEXT.md"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "#{Dir.home}/ghostconductor/etc/network-policy.json", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/network-policy.json"]
    system_command "/usr/bin/curl", args: ["-sL", "-o", "#{Dir.home}/ghostconductor/etc/container-policy.json", "https://github.com/GhostConductor/ghostconductor/releases/latest/download/container-policy.json"]
    system_command "/bin/rm", args: ["-f", "/tmp/prompts.tar.gz", "/tmp/context.tar.gz"]
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-rf", "#{Dir.home}/ghostconductor"]
    system_command "/bin/rm", args: ["-rf", "#{Dir.home}/.ghostconductor"]
    system_command "/usr/bin/env", args: ["docker", "rmi", "--force", "ghcr.io/ghostconductor/ghost:latest"]
    system_command "/usr/bin/env", args: ["docker", "rmi", "--force", "ghcr.io/ghostconductor/ghost:dev"]
  end

  # No zap stanza required

end
